module.exports = {
  apps: [
    {
      name: 'migration-orchestrator',
      cwd: '/home/ubuntu/workers',
      script: 'index.ts',
      interpreter: 'tsx',
      instances: 1,
      exec_mode: 'fork',
      env_file: '/home/ubuntu/workers/.env',
      env: { QUEUE_TYPE: 'orchestrator', WORKER_CONCURRENCY: '2', NODE_TLS_REJECT_UNAUTHORIZED: '0' },
      max_memory_restart: '256M',
      restart_delay: 5000,
      log_file: '/var/log/arham/migration-orchestrator.log',
      time: true,
    },
    {
      name: 'migration-users',
      cwd: '/home/ubuntu/workers',
      script: 'index.ts',
      interpreter: 'tsx',
      instances: 2,
      exec_mode: 'fork',
      env_file: '/home/ubuntu/workers/.env',
      env: { QUEUE_TYPE: 'users', WORKER_CONCURRENCY: '5', NODE_TLS_REJECT_UNAUTHORIZED: '0' },
      max_memory_restart: '400M',
      restart_delay: 5000,
      log_file: '/var/log/arham/migration-users.log',
      time: true,
    },
    {
      name: 'migration-messages',
      cwd: '/home/ubuntu/workers',
      script: 'index.ts',
      interpreter: 'tsx',
      instances: 2,
      exec_mode: 'fork',
      env_file: '/home/ubuntu/workers/.env',
      env: { QUEUE_TYPE: 'messages', WORKER_CONCURRENCY: '20', NODE_TLS_REJECT_UNAUTHORIZED: '0' },
      max_memory_restart: '400M',
      restart_delay: 5000,
      log_file: '/var/log/arham/migration-messages.log',
      time: true,
    },
  ],
};
